/**
 * 漢字データ
 * Kanji Data for Kanji Puzzle Game
 * 小学1年生〜6年生の教育漢字（各学年20字）+ 構成パズル用データ
 */

const kanjiData = {
    grade1: [
        { kanji: '一', reading: 'いち', meaning: 'ひとつ', hint: '☝️' },
        { kanji: '二', reading: 'に', meaning: 'ふたつ', hint: '✌️' },
        { kanji: '三', reading: 'さん', meaning: 'みっつ', hint: '🤟' },
        { kanji: '四', reading: 'し/よん', meaning: 'よっつ', hint: '4️⃣' },
        { kanji: '五', reading: 'ご', meaning: 'いつつ', hint: '🖐️' },
        { kanji: '六', reading: 'ろく', meaning: 'むっつ', hint: '6️⃣' },
        { kanji: '七', reading: 'しち/なな', meaning: 'ななつ', hint: '7️⃣' },
        { kanji: '八', reading: 'はち', meaning: 'やっつ', hint: '8️⃣' },
        { kanji: '九', reading: 'きゅう/く', meaning: 'ここのつ', hint: '9️⃣' },
        { kanji: '十', reading: 'じゅう', meaning: 'とお', hint: '🔟' },
        { kanji: '山', reading: 'やま', meaning: 'やま', hint: '⛰️' },
        { kanji: '川', reading: 'かわ', meaning: 'かわ', hint: '🏞️' },
        { kanji: '田', reading: 'た', meaning: 'たんぼ', hint: '🌾' },
        { kanji: '天', reading: 'てん', meaning: 'そら', hint: '🌤️' },
        { kanji: '上', reading: 'うえ', meaning: 'うえ', hint: '⬆️' },
        { kanji: '下', reading: 'した', meaning: 'した', hint: '⬇️' },
        { kanji: '大', reading: 'おお', meaning: 'おおきい', hint: '🐘' },
        { kanji: '小', reading: 'しょう/ちい', meaning: 'ちいさい', hint: '🐜' },
        { kanji: '人', reading: 'ひと', meaning: 'ひと', hint: '🧑' },
        { kanji: '木', reading: 'き/もく', meaning: 'き', hint: '🌳' },
    ],
    grade2: [
        { kanji: '花', reading: 'はな/か', meaning: 'はな', hint: '🌸' },
        { kanji: '貝', reading: 'かい', meaning: 'かいがら', hint: '🐚' },
        { kanji: '虫', reading: 'むし', meaning: 'むし', hint: '🐛' },
        { kanji: '魚', reading: 'さかな/ぎょ', meaning: 'さかな', hint: '🐟' },
        { kanji: '雲', reading: 'くも', meaning: 'くも', hint: '☁️' },
        { kanji: '雨', reading: 'あめ/う', meaning: 'あめ', hint: '🌧️' },
        { kanji: '風', reading: 'かぜ/ふう', meaning: 'かぜ', hint: '💨' },
        { kanji: '星', reading: 'ほし/せい', meaning: 'ほし', hint: '⭐' },
        { kanji: '森', reading: 'もり/しん', meaning: 'もり', hint: '🌲' },
        { kanji: '石', reading: 'いし/せき', meaning: 'いし', hint: '🪨' },
        { kanji: '空', reading: 'そら/くう', meaning: 'そら', hint: '🌤️' },
        { kanji: '正', reading: 'ただ/せい', meaning: 'ただしい', hint: '✅' },
        { kanji: '刀', reading: 'かたな/とう', meaning: 'かたな', hint: '🗡️' },
        { kanji: '弓', reading: 'ゆみ/きゅう', meaning: 'ゆみ', hint: '🏹' },
        { kanji: '車', reading: 'くるま/しゃ', meaning: 'くるま', hint: '🚗' },
        { kanji: '門', reading: 'かど/もん', meaning: 'もん', hint: '🚪' },
        { kanji: '間', reading: 'あいだ/かん', meaning: 'あいだ', hint: '📐' },
        { kanji: '力', reading: 'ちから/りき', meaning: 'ちから', hint: '💪' },
        { kanji: '林', reading: 'はやし/りん', meaning: 'はやし', hint: '🌳' },
        { kanji: '野', reading: 'の/や', meaning: 'のはら', hint: '🌿' },
    ],
    grade3: [
        { kanji: '春', reading: 'はる/しゅん', meaning: 'はる', hint: '🌷' },
        { kanji: '夏', reading: 'なつ/か', meaning: 'なつ', hint: '☀️' },
        { kanji: '秋', reading: 'あき/しゅう', meaning: 'あき', hint: '🍂' },
        { kanji: '冬', reading: 'ふゆ/とう', meaning: 'ふゆ', hint: '❄️' },
        { kanji: '海', reading: 'うみ/かい', meaning: 'うみ', hint: '🌊' },
        { kanji: '妹', reading: 'いもうと/まい', meaning: 'いもうと', hint: '👧' },
        { kanji: '兄', reading: 'あに/きょう', meaning: 'あに', hint: '👦' },
        { kanji: '弟', reading: 'おとうと/てい', meaning: 'おとうと', hint: '👦' },
        { kanji: '姉', reading: 'あね/し', meaning: 'あね', hint: '👧' },
        { kanji: '友', reading: 'とも/ゆう', meaning: 'ともだち', hint: '🤝' },
        { kanji: '明', reading: 'あき/めい', meaning: 'あかるい', hint: '💡' },
        { kanji: '声', reading: 'こえ/せい', meaning: 'こえ', hint: '📢' },
        { kanji: '色', reading: 'いろ/しょく', meaning: 'いろ', hint: '🎨' },
        { kanji: '町', reading: 'まち/ちょう', meaning: 'まち', hint: '🏘️' },
        { kanji: '村', reading: 'むら/そん', meaning: 'むら', hint: '🏡' },
        { kanji: '宇', reading: 'う', meaning: 'うち', hint: '🏠' },
        { kanji: '宿', reading: 'やど/しゅく', meaning: 'やど', hint: '🏨' },
        { kanji: '桥', reading: 'はし/きょう', meaning: 'はし', hint: '🌉' },
        { kanji: '音', reading: 'おと/おん', meaning: 'おと', hint: '🎵' },
        { kanji: '国', reading: 'くに/こく', meaning: 'くに', hint: '🗾' },
    ],
    grade4: [
        { kanji: '思', reading: 'おも/し', meaning: 'おもう', hint: '💭' },
        { kanji: '知', reading: 'し/ち', meaning: 'しる', hint: '🧠' },
        { kanji: '答', reading: 'こた/とう', meaning: 'こたえ', hint: '💡' },
        { kanji: '話', reading: 'はなし/わ', meaning: 'はなし', hint: '💬' },
        { kanji: '記', reading: 'き', meaning: 'しるす', hint: '📝' },
        { kanji: '送', reading: 'おく/そう', meaning: 'おくる', hint: '📮' },
        { kanji: '線', reading: 'せん', meaning: 'せん', hint: '〰️' },
        { kanji: '点', reading: 'てん', meaning: 'てん', hint: '⚪' },
        { kanji: '丸', reading: 'まる/がん', meaning: 'まるい', hint: '🔴' },
        { kanji: '角', reading: 'かど/かく', meaning: 'かど', hint: '📐' },
        { kanji: '重', reading: 'おも/じゅう', meaning: 'おもい', hint: '🏋️' },
        { kanji: '軽', reading: 'かる/けい', meaning: 'かるい', hint: '🪶' },
        { kanji: '速', reading: 'はや/そく', meaning: 'はやい', hint: '⚡' },
        { kanji: '遅', reading: 'おく/ち', meaning: 'おそい', hint: '🐢' },
        { kanji: '近', reading: 'ちか/きん', meaning: 'ちかい', hint: '📍' },
        { kanji: '遠', reading: 'とお/えん', meaning: 'とおい', hint: '🔭' },
        { kanji: '図', reading: 'ず/と', meaning: 'ず', hint: '🗺️' },
        { kanji: '画', reading: 'が/かく', meaning: 'えをかく', hint: '🖼️' },
        { kanji: '歌', reading: 'うた/か', meaning: 'うた', hint: '🎤' },
        { kanji: '楽', reading: 'たの/らく', meaning: 'たのしい', hint: '🎶' },
    ],
    grade5: [
        { kanji: '質', reading: 'しつ', meaning: 'しつもん', hint: '❓' },
        { kanji: '問', reading: 'と/もん', meaning: 'とい', hint: '❔' },
        { kanji: '反', reading: 'はん', meaning: 'はんたい', hint: '🔄' },
        { kanji: '映', reading: 'えい', meaning: 'うつる', hint: '🎬' },
        { kanji: '功', reading: 'こう', meaning: 'せいこう', hint: '🏆' },
        { kanji: '失', reading: 'しつ', meaning: 'うしなう', hint: '❌' },
        { kanji: '族', reading: 'ぞく', meaning: 'かぞく', hint: '👨‍👩‍👧‍👦' },
        { kanji: '感', reading: 'かん', meaning: 'かんじる', hint: '💭' },
        { kanji: '情', reading: 'じょう', meaning: 'きもち', hint: '💝' },
        { kanji: '意', reading: 'い', meaning: 'いみ', hint: '💡' },
        { kanji: '識', reading: 'しき', meaning: 'みとめる', hint: '👁️' },
        { kanji: '評', reading: 'ひょう', meaning: '評価', hint: '⭐' },
        { kanji: '価', reading: 'か', meaning: 'ねうち', hint: '💰' },
        { kanji: '勝', reading: 'か/しょう', meaning: 'かつ', hint: '🥇' },
        { kanji: '負', reading: 'ま/ふ', meaning: 'まける', hint: '🥈' },
        { kanji: '勇', reading: 'ゆう', meaning: 'いさましい', hint: '🦸' },
        { kanji: '験', reading: 'けん', meaning: 'ためす', hint: '🔬' },
        { kanji: '望', reading: 'のぞ/ぼう', meaning: 'のぞむ', hint: '🔭' },
        { kanji: '努', reading: 'ど', meaning: 'どりょく', hint: '💪' },
        { kanji: '費', reading: 'ひ', meaning: 'つかう', hint: '💴' },
    ],
    grade6: [
        { kanji: '圧', reading: 'あつ', meaning: 'おさえる', hint: '⚖️' },
        { kanji: '演', reading: 'えん', meaning: 'えんぎする', hint: '🎭' },
        { kanji: '機', reading: 'き', meaning: 'しかけ', hint: '⚙️' },
        { kanji: '創', reading: 'そう', meaning: 'つくる', hint: '🛠️' },
        { kanji: '規', reading: 'き', meaning: 'きそく', hint: '📏' },
        { kanji: '則', reading: 'そく', meaning: 'のり', hint: '📜' },
        { kanji: '果', reading: 'か', meaning: 'けっか', hint: '🍎' },
        { kanji: '報', reading: 'ほう', meaning: 'しらせる', hint: '📰' },
        { kanji: '権', reading: 'けん', meaning: 'ちから', hint: '⚡' },
        { kanji: '能', reading: 'のう', meaning: 'できる', hint: '🌟' },
        { kanji: '解', reading: 'かい/げ', meaning: 'とく', hint: '🔑' },
        { kanji: '説', reading: 'せつ', meaning: 'ときあかす', hint: '📖' },
        { kanji: '説', reading: 'ぜつ', meaning: 'せつめい', hint: '📢' },
        { kanji: '政', reading: 'せい', meaning: 'まつりごと', hint: '🏛️' },
        { kanji: '議', reading: 'ぎ', meaning: 'はかる', hint: '🏛️' },
        { kanji: '論', reading: 'ろん', meaning: 'ろんぱする', hint: '🗣️' },
        { kanji: '求', reading: 'きゅう', meaning: 'もとめる', hint: '🔍' },
        { kanji: '申', reading: 'しん', meaning: 'もうす', hint: '📝' },
        { kanji: '展', reading: 'てん', meaning: 'ひらく', hint: '🎪' },
        { kanji: '予', reading: 'よ', meaning: 'あらかじめ', hint: '🔮' },
    ],
};

/**
 * 漢字構成パズル用データ
 * 2つの部品を組み合わせてできる漢字
 */
const kanjiCompositions = [
    { left: '日', right: '月', result: '明', hint: 'あかるい' },
    { left: '木', right: '木', result: '林', hint: 'はやし' },
    { left: '人', right: '木', result: '休', hint: 'やすむ' },
    { left: '日', right: '立', result: '音', hint: 'おと' },
    { left: '田', right: '力', result: '男', hint: 'おとこ' },
    { left: '女', right: '子', result: '好', hint: 'すき' },
    { left: '山', right: '石', result: '岩', hint: 'いわ' },
    { left: '火', right: '山', result: '火山', hint: 'かざん' },
    { left: '大', right: '山', result: '岳', hint: 'だけ' },
    { left: '木', right: '目', result: '相', hint: 'あい' },
    { left: '口', right: '天', result: '呉', hint: 'くれ' },
    { left: '水', right: '工', result: '江', hint: 'え' },
    { left: '日', right: '本', result: '日本', hint: 'にほん' },
    { left: '月', right: '月', result: '朋', hint: 'とも' },
    { left: '人', right: '言', result: '信', hint: 'しんじる' },
    { left: '木', right: '下', result: '杷', hint: 'きのした' },
    { left: '立', right: '十', result: '辛', hint: 'からい' },
    { left: '目', right: '水', result: '涙', hint: 'なみだ' },
    { left: '手', right: '口', result: '拿', hint: 'とる' },
    { left: '心', right: '秋', result: '愁', hint: 'うれい' },
    { left: '糸', right: '色', result: '絶', hint: 'たえる' },
    { left: '石', right: '開', result: '砕', hint: 'くだく' },
    { left: '女', right: '少', result: '妙', hint: 'みょう' },
    { left: '山', right: '上', result: '岨', hint: 'やまのうえ' },
    { left: '白', right: '水', result: '泉', hint: 'いずみ' },
    { left: '日', right: '光', result: '晃', hint: 'あきらか' },
    { left: '人', right: '人', result: '从', hint: 'したがう' },
    { left: '口', right: '木', result: '呆', hint: 'あきれる' },
    { left: '力', right: '口', result: '加', hint: 'くわえる' },
    { left: '雨', right: '雲', result: '曇', hint: 'くもり' },
];

// エクスポート
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { kanjiData, kanjiCompositions };
}
